### ISSUE TITLE
Data preprocessing before starting the project

### ISSUE THREAD

**Issue by clhbbd** [runningcw/BowelNet#1]
Dear author, how were the individual bowel data obtained before the first stage of segmentation?

**Comment by cwangrun** [comment]
Hello, thanks for the question. Now the preprocessing step is provided in https://github.com/runningcw/BowelNet/blob/master/bowel_coarseseg/preprocessing.py.

This step consists of resampling, cropping abdomen body region, and downsampling. We average all 2-D slices to form a mean image and then apply thresholding on it to obtain the abdomen body region (excluding CT bed).

**Comment by clhbbd** [comment]
Hello, thank you very much for your reply. The pre-processing process is very smooth. Then I am very puzzled, why the data after the preprocessing is also through the "BowelCoarseSeg" cropping processing? Also puzzling is what “mode='infer'” means. What does the program infer do? Looking forward to your reply. Thank you.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "runningcw/BowelNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [runningcw/BowelNet] Data preprocessing before starting the project (Issue #1)





 
Hello, thanks for the question. Now the preprocessing step is provided in https://github.com/runningcw/BowelNet/blob/master/bowel_coarseseg/preprocessing.py.
 
This step consists of resampling, cropping abdomen body region, and downsampling. We average all 2-D slices to form a mean image and then apply thresholding on it to obtain the abdomen body region (excluding CT bed).

**Comment by cwangrun** [comment]
Hello, thanks for your questions. 

I guess the cropping processing you mentioned is "crop_resize". This is used for data augmentation during training. 

The "infer" mode means online testing in a sliding window fashion, you can ignore it in "datasets" and directly use the infer.py after models are trained.
