### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by loneblues** [runningcw/BowelNet#2]
Hi. 
Are your pretrained weights available? 
Or do we need to train based on our data? 
Thanks in advance.

**Comment by cwangrun** [comment]
Hi, 

Thanks so much for the question. The pretrained localisation model is available here: https://drive.google.com/drive/folders/1gCAlUXqWUPngfb2Kp86sttURpMNFRDZg?usp=drive_link
For the fine segmentation model, my suggestion is to train using your own data.

Best regards.
